"""
Report submission skill — draft and optionally submit bug bounty reports
to HackerOne and Bugcrowd via their APIs.

Modes:
  DRAFT_ONLY  (default) — generate a formatted report, don't submit
  SUBMIT      — submit to configured platform via API

Config (environment variables):
  HACKERONE_API_TOKEN   — HackerOne API token
  HACKERONE_USERNAME    — HackerOne username
  HACKERONE_PROGRAM     — program handle (e.g. "acme_corp")
  BUGCROWD_API_TOKEN    — Bugcrowd API token
  BUGCROWD_PROGRAM_CODE — Bugcrowd program code
  REPORT_PLATFORM       — "hackerone" | "bugcrowd" | "draft" (default: "draft")
  REPORT_MIN_SEVERITY   — minimum severity to submit (default: "medium")
"""
from __future__ import annotations

import json
import logging
import os
from dataclasses import dataclass
from pathlib import Path

import requests

from core.context import Context
from core.models import Finding, Severity

logger = logging.getLogger(__name__)

REPORT_DIR = Path("output/reports")


@dataclass
class DraftReport:
    finding:  Finding
    title:    str
    body:     str
    severity: str
    platform: str


# ── formatting ─────────────────────────────────────────────────────────────────

def _format_h1(f: Finding) -> tuple[str, str]:
    """Format a HackerOne-style report (title + markdown body)."""
    title = f.title

    cvss_line = ""
    if f.cvss:
        cvss_line = f"\n**CVSS Score:** {f.cvss.score} ({f.effective_severity.value.upper()})\n**CVSS Vector:** `{f.cvss.vector_string}`\n"

    proof_section = ""
    if f.proof.verified:
        proof_section = f"""
## Proof of Concept

**Verification method:** {f.proof.method}

**Request:**
```
{f.proof.request}
```

**Response:**
```
{f.proof.response[:1000]}
```
"""

    body = f"""## Summary
{f.description or f.title}

## Target
{f.target}

## Severity
{f.effective_severity.value.upper()}{cvss_line}

## Description
{f.description or "See title."}

{proof_section}
## Steps to Reproduce
1. Navigate to: `{f.target}`
2. Observe the issue described above.
3. See proof section for request/response evidence.

## Impact
{"See description." if not f.description else f.description[:300]}

## Remediation
{f.remediation or "Apply security best practices for this vulnerability class."}

## References
{chr(10).join(f"- {r}" for r in f.references) if f.references else "- https://owasp.org"}

---
*Generated by bug-bounty-ai*
"""
    return title, body


def _format_bugcrowd(f: Finding) -> tuple[str, str]:
    """Format a Bugcrowd-style submission."""
    title = f"[{f.effective_severity.value.upper()}] {f.title}"
    body = f"""**Target:** {f.target}
**Severity:** {f.effective_severity.value.upper()}
**Category:** {f.category.value}

**Description:**
{f.description or f.title}

**Steps to Reproduce:**
1. Access: {f.target}
2. {f.proof.method if f.proof.verified else 'Observe the issue.'}

**Expected Behavior:**
The vulnerability should not be present.

**Actual Behavior:**
{f.evidence or f.description or 'See title.'}

**Remediation:**
{f.remediation or 'Apply security best practices.'}

**References:**
{chr(10).join(f.references) if f.references else 'https://owasp.org'}
"""
    return title, body


# ── platform submission ──────────────────────────────────────────────────────

def _submit_hackerone(title: str, body: str, severity: str,
                       program: str, username: str, token: str) -> dict:
    """Submit a report to HackerOne API v1."""
    sev_map = {
        "critical": "critical", "high": "high",
        "medium": "medium", "low": "low", "info": "none"
    }
    payload = {
        "data": {
            "type": "report",
            "attributes": {
                "title":              title,
                "vulnerability_information": body,
                "impact":             body[:500],
                "severity_rating":    sev_map.get(severity, "medium"),
            },
            "relationships": {
                "program": {"data": {"type": "program", "attributes": {"handle": program}}}
            }
        }
    }
    r = requests.post(
        "https://api.hackerone.com/v1/reports",
        auth=(username, token),
        json=payload,
        headers={"Accept": "application/json"},
        timeout=15,
    )
    return {"status": r.status_code, "body": r.text[:500]}


def _submit_bugcrowd(title: str, body: str, severity: str,
                      program_code: str, token: str) -> dict:
    """Submit a report to Bugcrowd API."""
    sev_map = {"critical": 1, "high": 2, "medium": 3, "low": 4, "info": 5}
    payload = {
        "submission": {
            "title":        title,
            "description":  body,
            "severity":     sev_map.get(severity, 3),
            "target":       {"name": program_code},
        }
    }
    r = requests.post(
        f"https://api.bugcrowd.com/programs/{program_code}/submissions",
        headers={"Authorization": f"Token {token}",
                 "Content-Type": "application/json",
                 "Accept": "application/json"},
        json=payload,
        timeout=15,
    )
    return {"status": r.status_code, "body": r.text[:500]}


# ── entrypoint ────────────────────────────────────────────────────────────────

def run(context: Context) -> Context:
    REPORT_DIR.mkdir(parents=True, exist_ok=True)

    platform   = os.getenv("REPORT_PLATFORM",     "draft").lower()
    min_sev    = Severity.from_str(os.getenv("REPORT_MIN_SEVERITY", "medium"))
    h1_token   = os.getenv("HACKERONE_API_TOKEN",  "")
    h1_user    = os.getenv("HACKERONE_USERNAME",   "")
    h1_program = os.getenv("HACKERONE_PROGRAM",    "")
    bc_token   = os.getenv("BUGCROWD_API_TOKEN",   "")
    bc_program = os.getenv("BUGCROWD_PROGRAM_CODE","")

    # Validate submission config early
    if platform == "hackerone" and not all([h1_token, h1_user, h1_program]):
        logger.warning("HackerOne submission requires HACKERONE_API_TOKEN, HACKERONE_USERNAME, HACKERONE_PROGRAM — falling back to draft")
        platform = "draft"
    if platform == "bugcrowd" and not all([bc_token, bc_program]):
        logger.warning("Bugcrowd submission requires BUGCROWD_API_TOKEN, BUGCROWD_PROGRAM_CODE — falling back to draft")
        platform = "draft"

    findings = [f for f in context.findings
                if f.effective_severity >= min_sev]

    logger.info(f"Report submission: {len(findings)} findings ≥ {min_sev.value}, platform={platform}")

    drafted = submitted = 0
    submission_log = []

    for i, f in enumerate(findings, 1):
        sev = f.effective_severity.value

        if platform in ("hackerone", "draft"):
            title, body = _format_h1(f)
        else:
            title, body = _format_bugcrowd(f)

        # Always write draft to disk
        draft_path = REPORT_DIR / f"{i:02d}_{sev}_{f.source}_{f.category.value}.md"
        draft_path.write_text(
            f"# {title}\n\n**Platform:** {platform}\n\n{body}",
            encoding="utf-8",
        )
        drafted += 1

        # Submit if configured
        result = {"status": "draft", "finding": f.title}
        if platform == "hackerone":
            try:
                result = _submit_hackerone(title, body, sev, h1_program, h1_user, h1_token)
                if result["status"] in (200, 201):
                    submitted += 1
                    logger.info(f"Submitted to HackerOne: {title}")
                else:
                    logger.warning(f"HackerOne submission failed: {result}")
            except Exception as e:
                logger.error(f"HackerOne API error: {e}")
                result = {"status": "error", "error": str(e)}

        elif platform == "bugcrowd":
            try:
                result = _submit_bugcrowd(title, body, sev, bc_program, bc_token)
                if result["status"] in (200, 201):
                    submitted += 1
                    logger.info(f"Submitted to Bugcrowd: {title}")
                else:
                    logger.warning(f"Bugcrowd submission failed: {result}")
            except Exception as e:
                logger.error(f"Bugcrowd API error: {e}")
                result = {"status": "error", "error": str(e)}

        submission_log.append({
            "finding":   f.title,
            "severity":  sev,
            "platform":  platform,
            "result":    result,
            "draft":     str(draft_path),
        })

    # Write submission log
    log_path = REPORT_DIR / "submission_log.json"
    log_path.write_text(json.dumps(submission_log, indent=2), encoding="utf-8")

    logger.info(
        f"Report submission complete: {drafted} drafted, {submitted} submitted "
        f"to {platform}. Drafts in {REPORT_DIR}/"
    )

    context.insights.append({
        "type":      "report_submission",
        "platform":  platform,
        "drafted":   drafted,
        "submitted": submitted,
        "dir":       str(REPORT_DIR),
    })

    return context


skill = {"name": "report_submit", "run": run}
